name: Jira Ticket Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  jira-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract JIRA ticket from PR title or branch
        id: extract
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          echo "PR_TITLE=$PR_TITLE"
          echo "BRANCH_NAME=$BRANCH_NAME"
          # TICKET=$(echo "$PR_TITLE $BRANCH_NAME" | grep -oE '[A-Z]+-[0-9]+' | head -n1)
          TICKET=$(echo "$PR_TITLE $BRANCH_NAME" | grep -oE '[A-Za-z]+-[0-9]+' | head -n1 | tr '[:lower:]' '[:upper:]')
          if [[ -z "$TICKET" ]]; then
            echo "No JIRA ticket found in PR title or branch name."
            exit 1
          fi
          echo "ticket=$TICKET" >> $GITHUB_OUTPUT

      - name: Check JIRA ticket status
        env:
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          TICKET: ${{ steps.extract.outputs.ticket }}
        run: |
          if [[ -z "$JIRA_USER_EMAIL" || -z "$JIRA_API_TOKEN" || -z "$JIRA_BASE_URL" ]]; then
            echo "JIRA credentials or base URL not set."
            exit 1
          fi
          RESPONSE=$(curl -s -u "$JIRA_USER_EMAIL:$JIRA_API_TOKEN" \
            -H "Accept: application/json" \
            "$JIRA_BASE_URL/rest/api/2/issue/$TICKET")
          ERROR_MSG=$(echo "$RESPONSE" | jq -r '.errorMessages // empty')
          if [[ -n "$ERROR_MSG" ]]; then
            echo "JIRA ticket $TICKET not found: $ERROR_MSG"
            exit 1
          fi
          STATUS=$(echo "$RESPONSE" | jq -r '.fields.status.name')
          echo "JIRA ticket $TICKET status: $STATUS"
          if [[ "$STATUS" != "In Progress" ]]; then
            echo "JIRA ticket $TICKET is not In Progress (current status: $STATUS)"
            exit 1
          fi
