name: Require Jira Ticket (simple)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

env:
  # Edit to your prefixes
  TICKET_REGEX: '(?i)\b(?:PRD|OPS|JJ|FMS)-\d+\b'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate title contains ticket and issue exists in Jira
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}       # e.g., https://your-domain.atlassian.net
          JIRA_USER: ${{ secrets.JIRA_USER }}               # service account username (usually looks like an email)
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}     # API token created for that account
        run: |
          set -euo pipefail

          PR_TITLE="$(jq -r '.pull_request.title' < "$GITHUB_EVENT_PATH")"
          echo "PR title: $PR_TITLE"

          # Extract ticket key from PR title
          if ! echo "$PR_TITLE" | grep -Po "$TICKET_REGEX" >/dev/null; then
            echo "::error::No ticket key found in PR title. Expected something like PRD-1234 (regex: $TICKET_REGEX)"
            exit 1
          fi
          ISSUE_KEY="$(echo "$PR_TITLE" | grep -Po "$TICKET_REGEX" | head -n1 | tr '[:lower:]' '[:upper:]')"
          echo "Found ticket key: $ISSUE_KEY"

          # Call Jira API
          AUTH="$(printf '%s' "${JIRA_USER}:${JIRA_API_TOKEN}" | base64)"
          ISSUE_URL="${JIRA_BASE_URL}/rest/api/3/issue/${ISSUE_KEY}?fields=key,assignee"

          HTTP_CODE="$(curl -sS -w '%{http_code}' -o issue.json \
            -H "Authorization: Basic ${AUTH}" \
            -H "Accept: application/json" \
            "$ISSUE_URL")"

          if [[ "$HTTP_CODE" != "200" ]]; then
            echo "::error::Jira issue ${ISSUE_KEY} not found or API call failed (HTTP $HTTP_CODE)"
            cat issue.json || true
            exit 1
          fi

          ASSIGNEE_NAME="$(jq -r '.fields.assignee.displayName // "(unassigned)"' issue.json)"
          echo "✅ Jira issue ${ISSUE_KEY} exists. Assignee: ${ASSIGNEE_NAME}"
